version: '3.8'

services:
  app:
    build: .
    container_name: rag_agent
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - NVIDIA_VISIBLE_DEVICES=all  # Exposes all GPUs to the container
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility  # Enables CUDA capabilities
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    container_name: es_container
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: always

volumes:
  esdata:
    driver: local
